version: "3.8"
services:
  postgres_local_dev:
    container_name: postgresql_db_dev
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./:/var/lib/postgresql/data
    restart: always

#  postgres_local_test:
#    container_name: postgresql_db_test
#    image: postgres
#    ports:
#      - "5435:5432"
#    expose:
#      - "5432"
#    environment:
#      - POSTGRES_USER=${DB_USER}
#      - POSTGRES_PASSWORD=${DB_PASSWORD}
#      - POSTGRES_DB=${DB_NAME}
#      - PGDATA=/var/lib/postgresql/data/pgdata
#    volumes:
#      - ./:/var/lib/postgresql/test-data
#    restart: always

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
#      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
#    ports:
#      - "5050:80"
#    env_file:
#      - .env
#    depends_on:
#      - postgres_local_dev
#  mailhog:
#    image: mailhog/mailhog
#    logging:
#      driver: 'none'  # disable saving logs
#    ports:
#      - 1025:1025 # smtp server
#      - 8025:8025 # web ui
#    env_file:
#      - .env



